name = "adi"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "f14a24b8-65e8-4e65-93b6-14a1c606d422"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
